# Generated by Django 2.2.7 on 2019-11-28 19:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=70, unique=True, verbose_name='Client')),
            ],
        ),
        migrations.CreateModel(
            name='Invoicee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_name', models.CharField(max_length=50, unique=True, verbose_name='Recipient')),
                ('email_id', models.EmailField(max_length=254, unique=True, verbose_name='Email ID')),
                ('phone_num', models.CharField(max_length=15, unique=True, verbose_name='Phone')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50, unique=True, verbose_name='Location')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_name', models.CharField(max_length=70, unique=True, verbose_name='Vendor')),
                ('v_address', models.TextField(unique=True, verbose_name='Address')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_num', models.CharField(max_length=10, unique=True, verbose_name='Invoice Number')),
                ('po_number', models.CharField(max_length=20, null=True, unique=True, verbose_name='Purchase Order Number')),
                ('invoice_date', models.DateField(default=django.utils.timezone.now)),
                ('service', models.CharField(max_length=100)),
                ('unt_price', models.IntegerField(verbose_name='Unit Price')),
                ('n_days', models.IntegerField(verbose_name='No. of Days')),
                ('cab_price', models.IntegerField(default=0)),
                ('total_price_no_tax', models.IntegerField(blank=True, editable=False)),
                ('sgst', models.IntegerField(blank=True, verbose_name='SGST')),
                ('gst', models.IntegerField(blank=True, default=0, editable=False, verbose_name='GST')),
                ('grand_total', models.IntegerField(blank=True, editable=False)),
                ('po_upload', models.FileField(upload_to='po', verbose_name='Upload Purchase Order')),
                ('client_loc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoice.Location')),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoice.Client')),
                ('invoicee_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoice.Invoicee')),
                ('vendor_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoice.Vendor')),
            ],
        ),
    ]
