# Generated by Django 2.2.7 on 2019-11-28 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicee',
            name='acc_no',
            field=models.CharField(default='573702010008597', max_length=50, verbose_name='Account #'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoicee',
            name='bank',
            field=models.CharField(default='HDFC Bank', max_length=50, verbose_name='Bank Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoicee',
            name='branch',
            field=models.CharField(default='Madhapur', max_length=50, verbose_name='Branch Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoicee',
            name='ifsc',
            field=models.CharField(default='HDF78734', max_length=12, verbose_name='IFS Code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoicee',
            name='pan_no',
            field=models.CharField(default='CDYPP3627H', max_length=10, verbose_name='PAN #'),
            preserve_default=False,
        ),
    ]
