# Generated by Django 2.2.7 on 2019-11-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicee',
            name='phone_num',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
