# Generated by Django 2.2.7 on 2019-11-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_auto_20191122_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='c_adrress',
            field=models.TextField(verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='client',
            name='c_name',
            field=models.CharField(max_length=70, unique=True, verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='invoicee',
            name='email_id',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email ID'),
        ),
        migrations.AlterField(
            model_name='invoicee',
            name='phone_num',
            field=models.CharField(max_length=15, unique=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='invoicee',
            name='r_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Recipient'),
        ),
    ]
