# Generated by Django 2.2.7 on 2019-11-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_auto_20191122_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='service',
            field=models.CharField(max_length=100),
        ),
    ]
