# Generated by Django 2.2.7 on 2019-11-24 15:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0010_auto_20191124_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
